name: Build - Platform

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-build.yaml@main
    with:
      platform-name: codbex-platform-settings
      docker-build: false
      integration-tests: false
    secrets: inherit
